//
//  Zodiac.swift
//  PerfectMatch
//
//  Created by Nur Efsan Albas on 27.07.2022.
//

import Foundation
import SwiftUI

struct ZodiacSign : Identifiable {
    var id = UUID()
    var imageName: String
    var zodiacName: String
    var date: String
    var text: String
    var text2: String
}

var aries = ZodiacSign(imageName: "aries", zodiacName: "Aries", date: "March 21 - April 20",text:"Aries is the first sign of the zodiac. Being active and energetic are their defining characteristics. They have too much ego. Aries people are very practical. They cannot hide their excitement in the face of events. They move forward in their lives without losing their excitement. They are as creative as possible in the subjects they are curious about.",text2: "They want to prove themselves with what they do as they move towards their goals. They like to venture and they are productive. Sometimes they get into difficult situations because of their selfishness and impatience with their disobedience. At such moments, they leave the job they started without finishing it. Aries people always prefer to be in the foreground. They are fond of their independence.")
var taurus = ZodiacSign(imageName: "taurus", zodiacName: "Taurus", date: "April 21 - May 20",text:"Taurus is very focused and very careful as they move towards their goals. This is one of his greatest talents. They are extremely reliable in their personal relationships and are happy to help people. They always seek reliability and therefore do not put themselves at risk. Their success can sometimes envy others. Despite all this, they are warm-blooded people sought after by their surroundings.",text2:"Bulls, who seemed cold at first, are incredibly friendly people. Once they achieve their desires in life, no circumstance can pull them in any other direction. They see money as a tool to provide comfort. Luxury is important to them. They are skilled in acquiring property and property. They are successful in matters such as finance and investment.")
var gemini = ZodiacSign(imageName: "gemini", zodiacName: "Gemini", date: "May 21 - June 20",text:"Gemini people move very fast. They can do several jobs at the same time and easily adapt to anything. That's why they are known for their different characters. It is always possible to see these structures. They may be suddenly unhappy when they are overjoyed and happy, or they may suddenly soften when they are overly angry. It can make you feel as if there is no person you knew before.",text2: "They can be constantly misunderstood by their environment. They are so knowledgeable about a subject even they do not know that people may think they are experts in this field. They are attractive and intelligent with their practical intelligence. They are always on the lookout for new ideas. Even if they save with their own money, they can easily spend other people's money.")
var cancer = ZodiacSign(imageName: "cancer", zodiacName: "Cancer", date: "June 21 - July 22", text: "They are extremely sensitive and touchy. Their sense of responsibility is very developed. They are too detailed and perfectionist. Cancers are known for their emotionality and sensitivity. They are not easily understandable people as they expect the same sensitivity from everyone around them. ",text2: "They love their relatives and friends very much, but they cannot show it. They find it difficult to forgive people who have hurt them in any way and do not forget what they have done. They don't like arguments. They hide their feelings.")
var leo = ZodiacSign(imageName: "leo", zodiacName: "Leo", date: "July 23 - August 22",text:"Leos are born to lead and lead. They interfere with everything, they are arrogant. They always want to shine and be the focus in life. Organizational power is enormous. Making others accept their wishes is the 'must have' condition of their lives. They are charming and optimistic people who are impressive in their good times, smiling and love to help others.",text2: "Even if you misbehave with him, he will respond to you in a mature way. But after his patience has run out, he shows a stern attitude when necessary. They are very lucky. Their ruling planet, the Sun, brings them to light in their darkest days. Uneducated and underdeveloped Leo people become unbearable. They act like they have more in everything than they have.")
var virgo = ZodiacSign(imageName: "virgo", zodiacName: "Virgo", date: "August 23 - September 22",text:"Virgos are always looking for information because of their ruling planet, Mercury. Their intelligence is like a helper helping themselves. They care and examine every detail. Virgos become hardworking, determined and practical people, and the most important issue in their life is their work. While they like to help people they trust, they are cold towards people they don't believe in.",text2: "They work without rest all their lives. Even the way they rest can be tiring for others. They can often get lost in the details. Even in this period, they take care to do their work correctly and completely. Being frugal can make them stingy. They do not like to be too intimate, so they have a cold outlook towards people they have just met.")
var libra = ZodiacSign(imageName: "libra", zodiacName: "Libra", date: "September 23 - October 22",text:"Libras are very indecisive. They have a very strong attraction towards people. They are very balanced. You don't know what they are thinking. They examine the environments they are in very quickly and try to find out where the secret details are hidden. In order to master the subject, they do not work like crazy, they choose the environments where they will use the right logic.",text2: "Although they believe in the correctness of them deeds, they expects approval from other people. But you cannot criticize them. If you criticize, they will walk away from you and will not ask for your opinion again. They have high egos. Love and art are their secret world. They are not easy people and the people they will take into their lives must be above certain qualities.")
var scorpio = ZodiacSign(imageName: "scorpio", zodiacName: "Scorpio", date: "October 23 - November 22",text:"They live their lives passionately. They desire everything. They do not leave the work they start unfinished. They are very strong. Getting caught up in their emotions makes them dangerous individuals. They do not like arrogant and self-righteous people, and when they meet them, they humiliate themselves.",text2: "By reading what they know, they are not willing to compromise. They are very skeptical, they do not believe easily, but they stubbornly defend a subject they believe in until the end. While they work patiently and diligently in their work, they do their work without being ostentatious.")
var sagittarius = ZodiacSign(imageName: "sagittarius", zodiacName: "Sagittarius", date: "November 23 - December 20",text:"They are very successful in serious matters, philosophy, due to their highly developed ability to comprehend events. Sagittarians are sincere and optimistic. Sometimes the sign that learns the most from the mistakes they make, even if they are careless and contrary, is the sign Sagittarius.",text2: "They are overly fond of their freedom and very practical. The restriction of their lives bothers them. They take reckless risks. They like to research and discover things they don't know. Sagittarius are versatile people who are happy when they have several things to deal with at the same time. If they feel tired, it means they are bored with the subject.")
var capricorn = ZodiacSign(imageName: "capricorn", zodiacName: "Capricorn", date: "December 21 - January 19",text:"They constantly try to plan for the future, so they often fantasize. They find it difficult to relate to people because they are too busy with their work. Capricorns are characterized by their seriousness, conservatism, and strong will. Their hard work is enough to earn the respect of others. A true Capricorn has two key traits. Reliability and honesty.",text2: " They have a very developed sense of duty. Capricorns are very generous and very good confidants. They like to deal with concrete subjects all the time, and they carry out their business successfully with examples from the events found in nature. Therefore, they are also spiritually satisfied people. They are very tasteful, you can understand this from the design of their houses.")
var aquarius = ZodiacSign(imageName: "aquarius", zodiacName: "Aquarius", date: "Januray 20 - February 19",text:"Their imaginations are limitless and their thoughts are beyond immediate and intuitive. Aquarius signs are stubborn. They think they know everything. Aquarius people are affectionate. These people are not selfish. They want everyone to have the same opportunities, regardless of race, gender, or social status.",text2: "Sometimes they are stubborn and fixed-minded. It is very difficult to approach them, because no matter how close they are to you, there is an invisible distance between them. Their personal freedoms are so important to them that they may cut off their closest relationships and make all kinds of sacrifices in the name of their freedom. That's why family life is a little difficult for Aquarius.")
var pisces = ZodiacSign(imageName: "pisces", zodiacName: "Pisces", date: "February 20 - March 20",text:"Generosity, patience and sensitivity are the most important qualities of people born under this sign. They can easily convince people of themselves. They are honest, conscientious, docile and loyal. They can easily adapt to situations. Their dreams are important to them and they daydream often.",text2: "They are very sensitive and quickly affected by external factors. They are smart and cunning. They don't show you their angry nature and always wants to be the chosen one. Life is scary for them. Pisces are seen as fragile but very strong. They prefer to get over the events quickly and return to their life. Emotional frustrations cannot make them give up.")

var horoscope  = [aries,taurus,gemini,cancer,leo,virgo,libra,scorpio,sagittarius,capricorn,aquarius,pisces]



